services:
  # gateway:
  #   container_name: gateway
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.gateway
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '8080:8000'
  #   networks:
  #     - app-network
  #   depends_on:
  #     - rabbitmq

  # auth:
  #   container_name: auth
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.auth
  #   restart: always
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  #   depends_on:
  #     - rabbitmq

  # student:
  #   container_name: student
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.student
  #   restart: always
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  #   depends_on:
  #     - rabbitmq

  rabbitmq: # âœ… now inside services
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: attendance-management
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
